#!/bin/bash
export IFS=$'\n'
CMDNAME=`basename $0`
FILENAME_QUEUE="queue_youtube.txt"
if [ $# -ne 0 ]; then
    FILENAME_QUEUE=${1}
fi
echo "reading from "${FILENAME_QUEUE}"..."

mark_finished(){
        sed -i -e "s|${1}|#${1}|g" ${2}
}

for LINE in `cat ${FILENAME_QUEUE} | grep -v "^#"`
do

        TITLE=`echo ${LINE} | cut -f 1`
	URL=`echo ${LINE} | cut -f 2`

	if [ ${TITLE} = ${URL} ] ; then 
		TITLE=''
	fi


	echo ${TITLE}
	echo ${URL}

        if [ ${#URL} -lt 7 ] ; then
                continue
        fi

	if [ ${#TITLE} = 0 ] ; then
		youtube-dl --list-format ${URL} || continue
		youtube-dl --list-subs ${URL} || continue
		youtube-dl --encoding utf-8 --all-subs ${URL} && mark_finished "${LINE}" "${FILENAME_QUEUE}"
	else
		youtube-dl --encoding utf-8 ${URL} -o ${TITLE}.mp4 && mark_finished "${LINE}" "${FILENAME_QUEUE}"
	fi
done
