#!/bin/bash
export IFS=$'\n'
CMDNAME=`basename $0`

usage_exit() {
        echo "Usage: ${CMDNAME} [keyword]" 1>&2
        exit 1
}

if [ $# -ne 1 ]; then
	usage_exit
fi

keyword=`urlencode $1`
for url in `requests-html-get-html "https://tver.jp/search/catchup?keyword=${keyword}" HTML | grep -Po '(?<=href=")[^"]*' | grep -e corner -e feature` ; do
	echo 'https://tver.jp'$url
done
